name: Publish

on: workflow_dispatch

jobs:
    build:
        name: Build and Publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 8.x

            - name: Add Nuget source
              run: |
                  dotnet nuget add source --username lhauseux --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/lhauseux/index.json"

            - name: Install dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore

            - name: Pack
              run: dotnet pack --no-build --configuration Release

            - name: Publish
              run: dotnet nuget push ./Core/bin/Release/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
